# Generated by Django 4.2.21 on 2025-05-25 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('type', models.IntegerField(choices=[(1, 'Pontos corridos'), (2, 'Copa')], default=1)),
                ('has_group_stage', models.BooleanField()),
            ],
        ),
    ]
